apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-nodes
  namespace: tsmgr-{{.InstanceID}}
  labels:
    plan: {{ .Plan.Name }}
    org: {{ .OrgID }}
    space: {{ .SpaceID }}
    deleteOnUnprovision: "false"
spec:
  egress:
  - to:
  {{- range .Masters }}    
    - ipBlock:
        cidr: {{.IP}}/32
  {{- end }}
    ports:
    {{- range .Masters }}
    - protocol: {{ .Protocol}}
      port: {{.Port}}
    {{- end}}
  podSelector: {}
  policyTypes:
  - Egress
