---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dns-nwp
  labels:
    plan: {{ .Plan.Name }}
    org: {{ .OrgID }}
    space: {{ .SpaceID }}
    deleteOnUnprovision: "false"
spec:
  egress:
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
  podSelector: {}
  policyTypes:
  - Egress
  
