apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-s3-secret
  labels:
    plan: {{ .Plan.Name }}
    org: {{ .OrgID }}
    space: {{ .SpaceID }}
    deleteOnUnprovision: "false"
type: generic
stringData:
  accessKeyId: {{ .Plan.GetConfigValue "s3key" }}
  secretAccessKey: {{ .Plan.GetConfigValue "s3secret" }}
