{{- $nsname := printf "tsmgr-%s" .InstanceID -}}
{{- $instanceName := .Plan.GetConfigValue "pginstancename" -}}
{{- $existingPg := GetObjectByName $nsname "sql.tanzu.vmware.comi/v1" "Postgres" $instanceName -}}
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: {{ .Plan.GetConfigValue "pginstancename" }
spec:
  memory: {{ .Plan.GetConfigValue "ram" }}
  cpu: {{ .Values.cpu }} 
  storageClassName: {{ .Plan.GetConfigValue "storageClass" }}
  storageSize: {{ .Plan.GetConfigValue "diskSize" }}
{{ if ($existingPg) }
  monitorStorageClassName: {{ index $existingPg.Object "spec" "monitorStorageClassName" }}
{{ else }} 
  monitorStorageClassName: {{ .Plan.GetConfigValue "storageClass" }}
{{ end }}
  resources:
    monitor:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 450m
        memory: 100Mi
  pgConfig:
    dbname:  {{ $pginstancename }} 
    username: pgadmin
  serviceType: LoadBalancer
  highAvailability:
    enabled: {{  }}
  backupLocation:
    name: pg-backup-location
